import { mkdirSync, writeFileSync } from "node:fs";

const days = [
  { day: 1, title: "机场出行与会议开场", focus: "顺利完成抵达、值机和会议寒暄", travel: "airport", work: "meeting" },
  { day: 2, title: "酒店入住与商务邮件", focus: "处理住宿需求，写清楚电商业务邮件", travel: "hotel", work: "email" },
  { day: 3, title: "点餐交流与数据汇报", focus: "自然表达偏好，说明订单和转化数据", travel: "restaurant", work: "reporting" },
  { day: 4, title: "问路导航与客户沟通", focus: "确认路线，回应客户对订单和库存的诉求", travel: "directions", work: "client" },
  { day: 5, title: "机场转机与项目会议", focus: "处理延误和转机，推进会议决策", travel: "airport", work: "meeting" },
  { day: 6, title: "酒店服务与活动邮件", focus: "沟通房间服务，发送促销活动邮件", travel: "hotel", work: "email" },
  { day: 7, title: "餐厅结账与经营汇报", focus: "礼貌结账，复盘店铺表现和下一步动作", travel: "restaurant", work: "reporting" }
];

const seed = {
  airport: {
    category: "travel",
    title: "机场",
    subtitle: "值机、安检、登机、转机与行李",
    words: [
      ["boarding pass", "登机牌", "May I see your boarding pass?"],
      ["check-in counter", "值机柜台", "The check-in counter opens at six."],
      ["carry-on luggage", "随身行李", "This bag is my carry-on luggage."],
      ["checked baggage", "托运行李", "I have one checked baggage item."],
      ["security check", "安检", "Please prepare for the security check."],
      ["gate", "登机口", "Our gate has changed to B12."],
      ["terminal", "航站楼", "Which terminal is for international flights?"],
      ["departure", "出发", "The departure time is on the screen."],
      ["arrival", "到达", "The arrival hall is downstairs."],
      ["delay", "延误", "The flight has a two-hour delay."],
      ["transfer", "转机", "I need to make a transfer in Seoul."],
      ["customs", "海关", "You need to go through customs here."],
      ["immigration", "入境检查", "Immigration is just after the escalator."],
      ["passport", "护照", "Please keep your passport ready."],
      ["visa", "签证", "Do I need a visa for this trip?"],
      ["boarding time", "登机时间", "The boarding time is eight thirty."],
      ["window seat", "靠窗座位", "Could I have a window seat?"],
      ["aisle seat", "靠过道座位", "I prefer an aisle seat."],
      ["overweight bag", "超重行李", "Your suitcase is an overweight bag."],
      ["baggage claim", "行李提取处", "Baggage claim is on the first floor."],
      ["lost luggage", "遗失行李", "I need to report lost luggage."],
      ["direct flight", "直飞航班", "Is there a direct flight to London?"],
      ["connecting flight", "转机航班", "My connecting flight leaves soon."],
      ["flight number", "航班号", "What is your flight number?"],
      ["seat number", "座位号", "My seat number is 18A."],
      ["takeoff", "起飞", "Takeoff is scheduled for nine."],
      ["landing", "降落", "The landing was very smooth."],
      ["lounge", "候机休息室", "The lounge is near gate C3."],
      ["boarding announcement", "登机广播", "I heard the boarding announcement."],
      ["final call", "最后登机通知", "This is the final call for flight MU510."],
      ["ticket agent", "票务人员", "The ticket agent helped me change flights."],
      ["self-service kiosk", "自助值机机", "Use the self-service kiosk to print your pass."],
      ["excess fee", "超重费", "How much is the excess fee?"],
      ["liquid limit", "液体限制", "There is a liquid limit for carry-ons."],
      ["travel adapter", "旅行转换插头", "I packed a travel adapter in my bag."],
      ["currency exchange", "货币兑换", "Currency exchange is next to arrivals."],
      ["airport shuttle", "机场班车", "The airport shuttle leaves every twenty minutes."],
      ["tax-free shop", "免税店", "The tax-free shop is after security."],
      ["priority boarding", "优先登机", "Priority boarding starts first."],
      ["boarding group", "登机组别", "Please wait for your boarding group."],
      ["ticket change", "改签", "Can I make a ticket change?"],
      ["refund", "退款", "I would like to request a refund."],
      ["standby", "候补", "Can you put me on standby?"],
      ["departure board", "出发信息屏", "Check the departure board for updates."],
      ["arrival card", "入境卡", "Please fill out the arrival card."],
      ["security tray", "安检托盘", "Put your laptop in a security tray."],
      ["metal detector", "金属探测门", "Walk through the metal detector."],
      ["fragile sticker", "易碎标签", "Could you add a fragile sticker?"],
      ["baggage tag", "行李牌", "Keep your baggage tag safe."],
      ["travel insurance", "旅行保险", "Travel insurance covers flight delays."]
    ],
    sentenceScenes: ["值机", "安检", "登机", "转机", "行李", "延误", "座位", "海关", "改签", "问询"],
    sentences: [
      ["I'd like to check in for my flight.", "我想办理航班值机。"],
      ["Could you tell me where the security checkpoint is?", "请问安检口在哪里？"],
      ["Has boarding started for this flight?", "这个航班开始登机了吗？"],
      ["I have a connecting flight in two hours.", "我两小时后有一个转机航班。"],
      ["My suitcase has not arrived yet.", "我的行李箱还没有到。"],
      ["Could you help me check the delay status?", "你能帮我查一下延误情况吗？"],
      ["Is it possible to change to an aisle seat?", "可以换成靠过道座位吗？"],
      ["Where should I go for immigration?", "我应该去哪里办理入境检查？"],
      ["Can I change my ticket to an earlier flight?", "我可以改签到更早的航班吗？"],
      ["Which gate should I go to?", "我应该去哪个登机口？"],
      ["I only have one carry-on bag.", "我只有一个随身包。"],
      ["Do I need to take out my laptop?", "我需要把电脑拿出来吗？"],
      ["Please let me know if the gate changes.", "如果登机口变了请告诉我。"],
      ["How much time do I need for the transfer?", "转机需要预留多长时间？"],
      ["Where can I file a lost luggage report?", "我在哪里可以登记行李遗失？"],
      ["Is there any meal voucher for the delay?", "延误有餐券吗？"],
      ["Could my family sit together?", "我的家人可以坐在一起吗？"],
      ["I am here for a business trip.", "我是来出差的。"],
      ["What is the change fee?", "改签费是多少？"],
      ["Is there an airport shuttle to downtown?", "有去市区的机场班车吗？"]
    ]
  },
  hotel: {
    category: "travel",
    title: "酒店",
    subtitle: "入住、设施、客房服务与退房",
    words: [
      ["reservation", "预订", "I have a reservation under Li."],
      ["front desk", "前台", "The front desk is open all night."],
      ["check-in", "入住", "Check-in starts at three."],
      ["check-out", "退房", "Check-out is before noon."],
      ["room key", "房卡", "My room key does not work."],
      ["single room", "单人间", "I booked a single room."],
      ["double room", "双人间", "A double room is available tonight."],
      ["suite", "套房", "The suite has a city view."],
      ["deposit", "押金", "How much is the deposit?"],
      ["invoice", "发票", "Could I have an invoice?"],
      ["receipt", "收据", "Please send the receipt by email."],
      ["breakfast included", "含早餐", "Is breakfast included?"],
      ["wifi password", "无线密码", "What is the wifi password?"],
      ["room service", "客房服务", "Room service is available until ten."],
      ["housekeeping", "客房清洁", "Housekeeping will come this afternoon."],
      ["laundry service", "洗衣服务", "Do you offer laundry service?"],
      ["air conditioner", "空调", "The air conditioner is too loud."],
      ["heater", "暖气", "The heater is not working."],
      ["towel", "毛巾", "Could I get two more towels?"],
      ["pillow", "枕头", "I need an extra pillow."],
      ["blanket", "毯子", "Could you bring a blanket?"],
      ["minibar", "迷你吧", "Is the minibar free?"],
      ["safe", "保险箱", "There is a safe in the closet."],
      ["elevator", "电梯", "Take the elevator to the fifth floor."],
      ["lobby", "大堂", "Let's meet in the lobby."],
      ["concierge", "礼宾部", "The concierge can book a taxi."],
      ["wake-up call", "叫醒服务", "Please arrange a wake-up call."],
      ["late check-out", "延迟退房", "Can I request a late check-out?"],
      ["early check-in", "提前入住", "Is early check-in possible?"],
      ["non-smoking room", "无烟房", "I need a non-smoking room."],
      ["city view", "城市景观", "Does the room have a city view?"],
      ["quiet room", "安静房间", "I prefer a quiet room."],
      ["shuttle bus", "接驳车", "The shuttle bus goes to the airport."],
      ["gym", "健身房", "Where is the gym?"],
      ["swimming pool", "游泳池", "The swimming pool closes at nine."],
      ["business center", "商务中心", "The business center has a printer."],
      ["conference room", "会议室", "We booked a conference room."],
      ["maintenance", "维修", "Please send maintenance to my room."],
      ["hot water", "热水", "There is no hot water in the shower."],
      ["shower", "淋浴", "The shower pressure is low."],
      ["bathtub", "浴缸", "Does the room have a bathtub?"],
      ["adapter", "转换插头", "Can I borrow an adapter?"],
      ["luggage storage", "行李寄存", "Do you have luggage storage?"],
      ["taxi booking", "叫车服务", "I need taxi booking for tomorrow."],
      ["complimentary", "免费的", "Is the coffee complimentary?"],
      ["upgrade", "升级", "Can I get a room upgrade?"],
      ["floor", "楼层", "Which floor is my room on?"],
      ["amenities", "洗漱用品", "The amenities are in the bathroom."],
      ["service charge", "服务费", "Is the service charge included?"],
      ["confirmation number", "确认号", "Here is my confirmation number."]
    ],
    sentenceScenes: ["入住", "房间问题", "设施", "服务", "账单", "退房", "早餐", "交通", "商务", "请求"],
    sentences: [
      ["I have a reservation for tonight.", "我今晚有预订。"],
      ["The air conditioner in my room is not working.", "我房间的空调坏了。"],
      ["Could you tell me where the gym is?", "请问健身房在哪里？"],
      ["Could I order room service?", "我可以点客房服务吗？"],
      ["Could you prepare an invoice for me?", "能帮我准备发票吗？"],
      ["Can I have a late check-out?", "我可以延迟退房吗？"],
      ["What time is breakfast served?", "早餐几点供应？"],
      ["Could you book a taxi to the airport?", "能帮我预约去机场的出租车吗？"],
      ["I need to print a document for a meeting.", "我需要打印一份会议文件。"],
      ["Could I have an extra pillow, please?", "请再给我一个枕头好吗？"],
      ["The room key does not work.", "房卡打不开门。"],
      ["There is no hot water in the bathroom.", "浴室没有热水。"],
      ["Is the swimming pool open now?", "游泳池现在开放吗？"],
      ["Please clean my room this afternoon.", "请今天下午打扫我的房间。"],
      ["Can you email me the receipt?", "可以把收据发到我的邮箱吗？"],
      ["I would like to store my luggage here.", "我想把行李寄存在这里。"],
      ["Is breakfast included in my booking?", "我的预订包含早餐吗？"],
      ["When does the shuttle bus leave?", "接驳车什么时候出发？"],
      ["Is there a conference room available?", "有可用的会议室吗？"],
      ["Could you change me to a quieter room?", "能给我换到更安静的房间吗？"]
    ]
  },
  restaurant: {
    category: "travel",
    title: "点餐",
    subtitle: "预订、点餐、口味、过敏与结账",
    words: [
      ["menu", "菜单", "Could I see the menu?"],
      ["reservation", "订位", "We have a reservation for two."],
      ["table for two", "两人桌", "A table for two, please."],
      ["starter", "前菜", "We will share a starter."],
      ["main course", "主菜", "The main course is grilled fish."],
      ["dessert", "甜点", "What dessert do you recommend?"],
      ["beverage", "饮料", "The beverage list is on the back."],
      ["special", "特色菜", "Today's special is roast chicken."],
      ["recommendation", "推荐", "Do you have any recommendations?"],
      ["spicy", "辣的", "Is this dish spicy?"],
      ["mild", "清淡的", "Please make it mild."],
      ["vegetarian", "素食的", "Do you have vegetarian options?"],
      ["allergy", "过敏", "I have a peanut allergy."],
      ["seafood", "海鲜", "The seafood here is fresh."],
      ["beef", "牛肉", "I would like the beef noodles."],
      ["chicken", "鸡肉", "The chicken salad is popular."],
      ["pork", "猪肉", "Does this contain pork?"],
      ["noodles", "面条", "The noodles are handmade."],
      ["rice", "米饭", "Could I have rice on the side?"],
      ["soup", "汤", "The soup is very hot."],
      ["salad", "沙拉", "I'll start with a salad."],
      ["sauce", "酱汁", "Could you put the sauce on the side?"],
      ["side dish", "配菜", "The side dish is included."],
      ["portion", "份量", "The portion is quite large."],
      ["takeaway", "外带", "Can I get this for takeaway?"],
      ["dine in", "堂食", "We would like to dine in."],
      ["bill", "账单", "Could we have the bill?"],
      ["split the bill", "分开付款", "Can we split the bill?"],
      ["service charge", "服务费", "Is the service charge included?"],
      ["tip", "小费", "Should we leave a tip?"],
      ["cash", "现金", "Can I pay in cash?"],
      ["credit card", "信用卡", "Do you accept credit cards?"],
      ["QR code", "二维码", "Please scan the QR code to order."],
      ["waiter", "服务员", "The waiter brought water."],
      ["chef", "厨师", "The chef recommends this dish."],
      ["fresh", "新鲜的", "The vegetables taste fresh."],
      ["crispy", "酥脆的", "The duck skin is crispy."],
      ["tender", "嫩的", "The beef is very tender."],
      ["sweet", "甜的", "The dessert is not too sweet."],
      ["sour", "酸的", "The sauce is a little sour."],
      ["salty", "咸的", "This soup is too salty."],
      ["bitter", "苦的", "The coffee is slightly bitter."],
      ["hot pot", "火锅", "Hot pot is good for groups."],
      ["barbecue", "烧烤", "The barbecue smells great."],
      ["set meal", "套餐", "The set meal includes soup."],
      ["refill", "续杯", "Can I get a water refill?"],
      ["napkin", "餐巾", "Could we have more napkins?"],
      ["chopsticks", "筷子", "May I have extra chopsticks?"],
      ["fork", "叉子", "I need a fork, please."],
      ["receipt", "收据", "Could I have a receipt?"]
    ],
    sentenceScenes: ["入座", "推荐", "口味", "过敏", "点菜", "加点", "外带", "结账", "付款", "反馈"],
    sentences: [
      ["Do you have a table for two?", "有两人桌吗？"],
      ["What do you recommend today?", "今天你推荐什么？"],
      ["Could you make it less spicy?", "可以少放辣吗？"],
      ["I am allergic to peanuts.", "我对花生过敏。"],
      ["I would like to order this dish.", "我想点这道菜。"],
      ["Could we add one more soup?", "我们可以再加一份汤吗？"],
      ["Can I take the leftovers to go?", "剩菜可以打包吗？"],
      ["Could we have the bill, please?", "请给我们账单好吗？"],
      ["Do you accept mobile payment?", "你们接受手机支付吗？"],
      ["Everything was delicious, thank you.", "都很好吃，谢谢。"],
      ["We have a reservation under Wang.", "我们用王先生的名字订了位。"],
      ["Is this dish suitable for vegetarians?", "这道菜适合素食者吗？"],
      ["Please put the sauce on the side.", "请把酱汁放在旁边。"],
      ["Does this contain seafood?", "这道菜含海鲜吗？"],
      ["We will share the main courses.", "我们会一起分享主菜。"],
      ["Could I get a refill of water?", "可以给我续杯水吗？"],
      ["I'd like this for takeaway.", "这份我要外带。"],
      ["Can we split the bill?", "我们可以分开付款吗？"],
      ["Could you bring the receipt?", "可以拿收据给我吗？"],
      ["The soup is a little too salty.", "这个汤有点太咸了。"]
    ]
  },
  directions: {
    category: "travel",
    title: "问路",
    subtitle: "路线、交通、地标与确认方向",
    words: [
      ["direction", "方向", "Could you point me in the right direction?"],
      ["map", "地图", "The map shows a nearby station."],
      ["street", "街道", "This street goes to the museum."],
      ["avenue", "大道", "Turn left on the avenue."],
      ["intersection", "十字路口", "Meet me at the next intersection."],
      ["traffic light", "红绿灯", "Turn right at the traffic light."],
      ["crosswalk", "人行横道", "Use the crosswalk to cross the road."],
      ["corner", "拐角", "The cafe is on the corner."],
      ["block", "街区", "It is two blocks away."],
      ["landmark", "地标", "The tower is a famous landmark."],
      ["subway station", "地铁站", "The subway station is nearby."],
      ["bus stop", "公交站", "The bus stop is across the street."],
      ["taxi stand", "出租车站", "There is a taxi stand outside."],
      ["entrance", "入口", "The entrance is on your left."],
      ["exit", "出口", "Use exit B for the mall."],
      ["platform", "站台", "Platform two is for downtown trains."],
      ["line", "线路", "Take line two to People's Square."],
      ["transfer", "换乘", "You need to transfer at Central Station."],
      ["fare", "票价", "The fare is three dollars."],
      ["ticket machine", "售票机", "Buy a ticket at the ticket machine."],
      ["one-way ticket", "单程票", "I need a one-way ticket."],
      ["round-trip ticket", "往返票", "A round-trip ticket is cheaper."],
      ["walking distance", "步行距离", "The hotel is within walking distance."],
      ["shortcut", "近路", "This alley is a shortcut."],
      ["detour", "绕路", "There is a detour because of construction."],
      ["downtown", "市中心", "The bus goes downtown."],
      ["uptown", "住宅区方向", "Take the uptown train."],
      ["nearby", "附近", "Is there a pharmacy nearby?"],
      ["far", "远的", "The airport is far from here."],
      ["straight ahead", "一直往前", "Go straight ahead for five minutes."],
      ["turn left", "左转", "Turn left after the bank."],
      ["turn right", "右转", "Turn right at the bookstore."],
      ["across from", "在对面", "The hotel is across from the park."],
      ["next to", "在旁边", "The ATM is next to the elevator."],
      ["behind", "在后面", "The parking lot is behind the building."],
      ["in front of", "在前面", "The bus is in front of the station."],
      ["north", "北", "The museum is north of the river."],
      ["south", "南", "The market is south of the hotel."],
      ["east", "东", "The office is east of the station."],
      ["west", "西", "The park is west of the square."],
      ["bridge", "桥", "Cross the bridge and turn left."],
      ["tunnel", "隧道", "The tunnel leads to the old town."],
      ["escalator", "扶梯", "Take the escalator down."],
      ["elevator", "电梯", "Use the elevator for platform three."],
      ["stairs", "楼梯", "The stairs are on the right."],
      ["parking lot", "停车场", "The parking lot is full."],
      ["pharmacy", "药店", "I am looking for a pharmacy."],
      ["museum", "博物馆", "How do I get to the museum?"],
      ["tourist information", "游客信息中心", "Tourist information is near the exit."],
      ["lost", "迷路的", "I think I am lost."]
    ],
    sentenceScenes: ["开口问路", "步行", "地铁", "公交", "确认", "地标", "换乘", "买票", "迷路", "感谢"],
    sentences: [
      ["Excuse me, how do I get to the station?", "打扰一下，我怎么去车站？"],
      ["Is it within walking distance?", "步行能到吗？"],
      ["Which subway line should I take?", "我应该坐哪条地铁线？"],
      ["Where is the nearest bus stop?", "最近的公交站在哪里？"],
      ["So I turn right at the next light, correct?", "所以我在下一个红绿灯右转，对吗？"],
      ["Is there a landmark nearby?", "附近有什么地标吗？"],
      ["Do I need to transfer?", "我需要换乘吗？"],
      ["Where can I buy a ticket?", "我在哪里可以买票？"],
      ["I think I am lost.", "我觉得我迷路了。"],
      ["Thank you for your help.", "谢谢你的帮助。"],
      ["Could you show me on the map?", "你能在地图上指给我看吗？"],
      ["How long does it take on foot?", "步行需要多久？"],
      ["Which exit should I use?", "我应该走哪个出口？"],
      ["Does this bus go downtown?", "这辆公交去市中心吗？"],
      ["Let me repeat the directions.", "我复述一下路线。"],
      ["The hotel is across from the park, right?", "酒店在公园对面，对吗？"],
      ["Where should I transfer to line two?", "我在哪里换乘二号线？"],
      ["Can I use a credit card at the ticket machine?", "售票机可以用信用卡吗？"],
      ["Could you call a taxi for me?", "你能帮我叫辆出租车吗？"],
      ["I really appreciate it.", "非常感谢。"]
    ]
  },
  meeting: {
    category: "work",
    title: "会议",
    subtitle: "电商项目会议、决策、跟进与协作",
    words: [
      ["agenda", "议程", "The agenda has three topics."],
      ["objective", "目标", "Our objective is to improve conversion."],
      ["stakeholder", "相关方", "We need feedback from key stakeholders."],
      ["alignment", "对齐", "The meeting is for alignment."],
      ["action item", "行动项", "Each action item needs an owner."],
      ["owner", "负责人", "Who is the owner of this task?"],
      ["deadline", "截止日期", "The deadline is next Friday."],
      ["follow-up", "跟进", "I will send a follow-up email."],
      ["decision", "决定", "We need a decision today."],
      ["proposal", "方案", "This proposal focuses on repeat purchases."],
      ["scope", "范围", "Let's define the project scope."],
      ["priority", "优先级", "Checkout issues are the top priority."],
      ["timeline", "时间线", "The timeline is tight but realistic."],
      ["milestone", "里程碑", "Launch is the next milestone."],
      ["risk", "风险", "Inventory shortage is a risk."],
      ["blocker", "阻碍", "Payment integration is the main blocker."],
      ["dependency", "依赖", "The campaign depends on product photos."],
      ["resource", "资源", "We need more design resources."],
      ["budget", "预算", "The budget covers paid ads."],
      ["approval", "审批", "We need approval from finance."],
      ["retailer", "零售商", "The retailer joined our marketplace."],
      ["marketplace", "电商平台", "The marketplace has strong traffic."],
      ["seller", "商家", "The seller needs onboarding support."],
      ["buyer", "买家", "The buyer expects fast delivery."],
      ["SKU", "库存单位", "This SKU is our best seller."],
      ["inventory", "库存", "Inventory is low for the red model."],
      ["promotion", "促销", "The promotion starts on Monday."],
      ["discount", "折扣", "The discount is limited to members."],
      ["conversion rate", "转化率", "The conversion rate improved last week."],
      ["traffic", "流量", "Traffic from social ads is growing."],
      ["cart abandonment", "购物车放弃", "Cart abandonment is still high."],
      ["checkout", "结账流程", "Checkout should be faster."],
      ["payment gateway", "支付网关", "The payment gateway needs testing."],
      ["fulfillment", "履约", "Fulfillment speed affects ratings."],
      ["shipping fee", "运费", "The shipping fee is too high."],
      ["return policy", "退货政策", "The return policy must be clear."],
      ["customer review", "客户评价", "Customer reviews influence conversion."],
      ["rating", "评分", "The rating dropped after delays."],
      ["campaign", "活动", "The campaign targets new users."],
      ["landing page", "落地页", "The landing page needs stronger copy."],
      ["A/B test", "A/B 测试", "We will run an A/B test."],
      ["brief", "需求简报", "Please share the creative brief."],
      ["minutes", "会议纪要", "I will write the meeting minutes."],
      ["consensus", "共识", "We reached consensus on pricing."],
      ["assumption", "假设", "That assumption needs validation."],
      ["constraint", "限制条件", "The main constraint is time."],
      ["trade-off", "取舍", "There is a trade-off between speed and cost."],
      ["escalation", "升级处理", "This issue needs escalation."],
      ["recap", "回顾总结", "Let's do a quick recap."],
      ["next step", "下一步", "The next step is seller outreach."]
    ],
    sentenceScenes: ["开场", "目标", "讨论", "分歧", "数据", "决策", "行动项", "风险", "总结", "会后"],
    sentences: [
      ["Let's start with the agenda.", "我们先看会议议程。"],
      ["The goal is to increase checkout conversion.", "目标是提升结账转化率。"],
      ["Could you walk us through the proposal?", "你能带我们过一下方案吗？"],
      ["I see your point, but I have one concern.", "我理解你的观点，但我有一个顾虑。"],
      ["The data shows cart abandonment is increasing.", "数据显示购物车放弃率在上升。"],
      ["Can we make a decision today?", "我们今天能做决定吗？"],
      ["I will own the follow-up with sellers.", "我负责跟进商家。"],
      ["The biggest risk is low inventory.", "最大的风险是库存不足。"],
      ["Let me recap the next steps.", "我来总结下一步。"],
      ["I will send the meeting minutes after this call.", "会后我会发送会议纪要。"],
      ["Thanks everyone for joining on time.", "感谢大家准时参加。"],
      ["We need alignment before the campaign launch.", "活动上线前我们需要对齐。"],
      ["What trade-offs are we making here?", "这里我们在做什么取舍？"],
      ["Can we pause and clarify the scope?", "我们可以暂停一下并明确范围吗？"],
      ["Traffic is strong, but conversion is weak.", "流量不错，但转化偏弱。"],
      ["I support option B because it is faster.", "我支持方案 B，因为它更快。"],
      ["Please add the deadline to each action item.", "请给每个行动项加上截止日期。"],
      ["Payment testing is still a blocker.", "支付测试仍然是阻碍。"],
      ["Do we have consensus on the launch date?", "我们对上线日期达成共识了吗？"],
      ["Let's follow up in the project channel.", "我们在项目群里继续跟进。"]
    ]
  },
  email: {
    category: "work",
    title: "邮件",
    subtitle: "电商协作邮件、活动同步、问题跟进",
    words: [
      ["subject line", "邮件主题", "The subject line should be clear."],
      ["recipient", "收件人", "Add the buyer as a recipient."],
      ["cc", "抄送", "Please cc the operations team."],
      ["bcc", "密送", "Use bcc for the mailing list."],
      ["attachment", "附件", "The price list is in the attachment."],
      ["draft", "草稿", "I saved the email as a draft."],
      ["reply", "回复", "Please reply by tomorrow."],
      ["forward", "转发", "Can you forward the seller update?"],
      ["inbox", "收件箱", "My inbox is full today."],
      ["thread", "邮件串", "Let's keep everything in this thread."],
      ["greeting", "问候语", "Use a professional greeting."],
      ["opening", "开头", "The opening explains the purpose."],
      ["closing", "结尾", "The closing includes next steps."],
      ["signature", "签名", "Your signature needs a phone number."],
      ["template", "模板", "Use the campaign email template."],
      ["update", "更新", "Here is a quick update."],
      ["request", "请求", "This is a request for approval."],
      ["confirmation", "确认", "We need written confirmation."],
      ["clarification", "澄清", "I need clarification on the price."],
      ["deadline", "截止日期", "The deadline is Friday noon."],
      ["campaign calendar", "活动日历", "The campaign calendar changed."],
      ["product listing", "商品详情页", "The product listing needs new images."],
      ["price adjustment", "调价", "The price adjustment starts tonight."],
      ["coupon code", "优惠码", "The coupon code expires soon."],
      ["flash sale", "限时抢购", "The flash sale begins at eight."],
      ["seller center", "商家后台", "Check the seller center for alerts."],
      ["order issue", "订单问题", "The email is about an order issue."],
      ["tracking number", "物流单号", "Please include the tracking number."],
      ["refund request", "退款申请", "A refund request needs review."],
      ["return label", "退货标签", "Send the return label to the customer."],
      ["stock update", "库存更新", "We need a stock update today."],
      ["out of stock", "缺货", "This item is out of stock."],
      ["restock date", "补货日期", "What is the restock date?"],
      ["launch plan", "上线计划", "The launch plan is attached."],
      ["creative assets", "创意素材", "Creative assets are due tomorrow."],
      ["banner copy", "横幅文案", "The banner copy needs approval."],
      ["legal review", "法务审核", "The claim needs legal review."],
      ["approval chain", "审批链路", "The approval chain is too long."],
      ["urgent", "紧急", "Mark it urgent only when necessary."],
      ["FYI", "供参考", "FYI, the promotion is live."],
      ["ETA", "预计完成时间", "What is the ETA for the fix?"],
      ["SLA", "服务时限", "The SLA is twenty-four hours."],
      ["apology", "道歉", "Start with a sincere apology."],
      ["resolution", "解决方案", "The resolution is a replacement."],
      ["escalation", "升级", "This requires escalation to logistics."],
      ["summary", "摘要", "Add a short summary at the top."],
      ["bullet point", "项目符号", "Use bullet points for clarity."],
      ["tone", "语气", "The tone should be polite."],
      ["proofread", "校对", "Please proofread before sending."],
      ["send", "发送", "Do not send until finance approves."]
    ],
    sentenceScenes: ["开头", "更新", "请求", "澄清", "附件", "截止", "订单", "活动", "道歉", "结尾"],
    sentences: [
      ["I hope you are doing well.", "希望你一切顺利。"],
      ["I am writing to share a quick campaign update.", "我写信是想同步一个活动更新。"],
      ["Could you approve the banner copy by noon?", "你能在中午前审批横幅文案吗？"],
      ["Could you clarify the final discount rate?", "你能确认最终折扣率吗？"],
      ["Please find the launch plan attached.", "请查收附件中的上线计划。"],
      ["The creative assets are due tomorrow.", "创意素材明天截止。"],
      ["We are checking the order issue with logistics.", "我们正在和物流核查订单问题。"],
      ["The flash sale will go live at eight tonight.", "限时抢购今晚八点上线。"],
      ["We apologize for the delay in delivery.", "我们为配送延误道歉。"],
      ["Thank you, and I look forward to your feedback.", "谢谢，期待你的反馈。"],
      ["I wanted to follow up on the stock update.", "我想跟进一下库存更新。"],
      ["Here is the latest status from the seller team.", "以下是商家团队的最新状态。"],
      ["Could you send the tracking number?", "你能发送物流单号吗？"],
      ["Please confirm if the item is back in stock.", "请确认该商品是否已补货。"],
      ["The report is attached for your review.", "报告已附上，请你审阅。"],
      ["Please reply by Friday noon.", "请在周五中午前回复。"],
      ["The customer requested a refund.", "客户申请了退款。"],
      ["The coupon code expires this Sunday.", "优惠码本周日过期。"],
      ["We are sorry for the inconvenience.", "给你带来不便我们深感抱歉。"],
      ["Please let me know if you have any questions.", "如有问题请告诉我。"]
    ]
  },
  reporting: {
    category: "work",
    title: "汇报",
    subtitle: "电商指标、复盘、趋势与行动建议",
    words: [
      ["dashboard", "数据看板", "The dashboard updates every hour."],
      ["metric", "指标", "Conversion is our key metric."],
      ["KPI", "关键绩效指标", "GMV is one of our KPIs."],
      ["GMV", "成交总额", "GMV increased by twelve percent."],
      ["revenue", "收入", "Revenue grew month over month."],
      ["gross margin", "毛利率", "Gross margin improved after pricing changes."],
      ["order volume", "订单量", "Order volume peaked on Friday."],
      ["average order value", "客单价", "Average order value is rising."],
      ["conversion rate", "转化率", "The conversion rate is below target."],
      ["click-through rate", "点击率", "The click-through rate improved."],
      ["impression", "曝光", "Impressions doubled after the campaign."],
      ["traffic source", "流量来源", "Paid search is the top traffic source."],
      ["organic traffic", "自然流量", "Organic traffic is stable."],
      ["paid traffic", "付费流量", "Paid traffic became more expensive."],
      ["bounce rate", "跳出率", "The bounce rate is too high."],
      ["retention", "留存", "Retention is stronger among members."],
      ["repeat purchase", "复购", "Repeat purchase grew this month."],
      ["refund rate", "退款率", "The refund rate needs attention."],
      ["return rate", "退货率", "Return rate is high for apparel."],
      ["fulfillment time", "履约时长", "Fulfillment time dropped by one day."],
      ["on-time delivery", "准时送达", "On-time delivery is ninety-five percent."],
      ["inventory turnover", "库存周转", "Inventory turnover is faster now."],
      ["stockout", "断货", "Stockouts hurt sales last week."],
      ["sell-through rate", "售罄率", "Sell-through rate is above forecast."],
      ["forecast", "预测", "The forecast assumes steady demand."],
      ["trend", "趋势", "The trend is positive."],
      ["insight", "洞察", "The main insight is price sensitivity."],
      ["driver", "驱动因素", "Free shipping was a major driver."],
      ["root cause", "根因", "The root cause is poor page loading."],
      ["variance", "差异", "The variance comes from ad spend."],
      ["benchmark", "基准", "We compare results with the benchmark."],
      ["target", "目标", "The target is ten percent growth."],
      ["performance", "表现", "Performance improved after optimization."],
      ["underperform", "表现不佳", "This SKU continues to underperform."],
      ["overperform", "表现超预期", "The gift set overperformed."],
      ["segment", "细分人群", "The member segment buys more often."],
      ["cohort", "同期群", "The May cohort retained better."],
      ["funnel", "漏斗", "The funnel shows a checkout drop."],
      ["baseline", "基线", "We need a baseline before testing."],
      ["sample size", "样本量", "The sample size is still small."],
      ["statistical significance", "统计显著性", "The result reached statistical significance."],
      ["month over month", "环比", "Sales grew month over month."],
      ["year over year", "同比", "Revenue is up year over year."],
      ["action plan", "行动计划", "The action plan has three steps."],
      ["recommendation", "建议", "My recommendation is to reduce shipping fees."],
      ["next quarter", "下季度", "Next quarter focuses on retention."],
      ["summary slide", "总结页", "The summary slide needs one key message."],
      ["appendix", "附录", "Details are in the appendix."],
      ["data source", "数据源", "The data source is the order table."],
      ["data quality", "数据质量", "Data quality is reliable."]
    ],
    sentenceScenes: ["开场", "核心指标", "趋势", "问题", "原因", "细分", "实验", "建议", "风险", "收尾"],
    sentences: [
      ["Today I will report on last week's store performance.", "今天我汇报上周店铺表现。"],
      ["GMV increased by twelve percent week over week.", "GMV 周环比增长了 12%。"],
      ["The main trend is stronger mobile traffic.", "主要趋势是移动端流量更强。"],
      ["The biggest issue is a higher refund rate.", "最大问题是退款率升高。"],
      ["The root cause appears to be delayed shipping.", "根因似乎是配送延迟。"],
      ["Members showed a higher repeat purchase rate.", "会员显示出更高的复购率。"],
      ["The A/B test result is not significant yet.", "A/B 测试结果还不显著。"],
      ["My recommendation is to improve checkout speed.", "我的建议是提升结账速度。"],
      ["The main risk is another stockout.", "主要风险是再次断货。"],
      ["I will share the full dashboard after the meeting.", "会后我会分享完整数据看板。"],
      ["The report has three parts.", "这份汇报分为三部分。"],
      ["Conversion rate missed the target by two points.", "转化率比目标低两个百分点。"],
      ["Paid traffic is becoming more expensive.", "付费流量正在变贵。"],
      ["Cart abandonment rose on mobile devices.", "移动端购物车放弃率上升了。"],
      ["Free shipping was the biggest driver.", "包邮是最大的驱动因素。"],
      ["New customers spent less than members.", "新客户消费低于会员。"],
      ["We need a larger sample size before deciding.", "决策前我们需要更大的样本量。"],
      ["I suggest testing a lower shipping threshold.", "我建议测试更低的包邮门槛。"],
      ["Inventory is not enough for the next campaign.", "库存不足以支撑下一次活动。"],
      ["That concludes my update.", "我的汇报到这里结束。"]
    ]
  },
  client: {
    category: "work",
    title: "客户沟通",
    subtitle: "电商客户咨询、投诉、退款、物流与续单",
    words: [
      ["customer", "客户", "The customer asked about delivery."],
      ["client", "客户", "This client buys in large volume."],
      ["inquiry", "咨询", "We received a product inquiry."],
      ["complaint", "投诉", "The complaint is about late delivery."],
      ["issue", "问题", "We are investigating the issue."],
      ["case", "工单", "The support case is open."],
      ["ticket", "服务单", "Please update the support ticket."],
      ["response time", "响应时间", "Response time affects satisfaction."],
      ["SLA", "服务时限", "We must meet the SLA."],
      ["satisfaction", "满意度", "Customer satisfaction improved."],
      ["expectation", "期望", "Set clear expectations."],
      ["apology", "道歉", "A sincere apology helps."],
      ["empathy", "同理心", "Show empathy before explaining."],
      ["solution", "解决方案", "Offer a practical solution."],
      ["compensation", "补偿", "We can offer compensation."],
      ["refund", "退款", "The refund will take three days."],
      ["replacement", "换货", "We can send a replacement."],
      ["return", "退货", "The return window is thirty days."],
      ["warranty", "保修", "The warranty covers defects."],
      ["defect", "缺陷", "The product has a defect."],
      ["damaged", "损坏的", "The package arrived damaged."],
      ["missing item", "漏发商品", "The order has a missing item."],
      ["wrong item", "错发商品", "The customer received the wrong item."],
      ["order number", "订单号", "May I have your order number?"],
      ["tracking number", "物流单号", "The tracking number is in the email."],
      ["delivery status", "配送状态", "I will check the delivery status."],
      ["estimated delivery", "预计送达", "The estimated delivery is Friday."],
      ["shipping address", "收货地址", "Please confirm the shipping address."],
      ["billing address", "账单地址", "The billing address is different."],
      ["invoice", "发票", "We can issue an invoice."],
      ["payment failure", "支付失败", "The payment failure was temporary."],
      ["chargeback", "拒付", "The bank opened a chargeback."],
      ["coupon", "优惠券", "We can offer a coupon."],
      ["loyalty points", "会员积分", "Loyalty points were added."],
      ["VIP customer", "VIP 客户", "This is a VIP customer."],
      ["bulk order", "批量订单", "The client wants a bulk order."],
      ["quotation", "报价", "Please send a quotation."],
      ["purchase order", "采购订单", "The purchase order is approved."],
      ["contract", "合同", "The contract needs signature."],
      ["renewal", "续约", "Renewal is due next month."],
      ["upsell", "追加销售", "There is an upsell opportunity."],
      ["cross-sell", "交叉销售", "We can cross-sell accessories."],
      ["feedback", "反馈", "Customer feedback is valuable."],
      ["review", "评价", "Please leave a review."],
      ["escalate", "升级处理", "We should escalate this issue."],
      ["resolve", "解决", "We need to resolve it today."],
      ["follow up", "跟进", "I will follow up tomorrow."],
      ["confirm", "确认", "Please confirm the address."],
      ["appreciate", "感谢", "We appreciate your patience."],
      ["relationship", "关系", "A good relationship builds trust."]
    ],
    sentenceScenes: ["问候", "核实", "安抚", "物流", "退款", "换货", "报价", "投诉", "跟进", "结束"],
    sentences: [
      ["Thank you for contacting us.", "感谢你联系我们。"],
      ["May I have your order number, please?", "请问可以提供订单号吗？"],
      ["I understand how frustrating this must be.", "我理解这一定很令人沮丧。"],
      ["Let me check the delivery status for you.", "我帮你查询配送状态。"],
      ["The refund will be processed within three business days.", "退款将在三个工作日内处理。"],
      ["We can send a replacement at no extra cost.", "我们可以免费寄送换货。"],
      ["I will send you a quotation today.", "我今天会给你发送报价。"],
      ["We are sorry that the item arrived damaged.", "很抱歉商品送达时已损坏。"],
      ["I will follow up with logistics and update you.", "我会跟进物流并更新你。"],
      ["Thank you for your patience and understanding.", "感谢你的耐心和理解。"],
      ["Could you confirm your shipping address?", "你能确认一下收货地址吗？"],
      ["I will open a support ticket for this case.", "我会为这个问题创建服务单。"],
      ["We appreciate your feedback.", "我们感谢你的反馈。"],
      ["The package is expected to arrive on Friday.", "包裹预计周五送达。"],
      ["A coupon has been added to your account.", "优惠券已经添加到你的账户。"],
      ["Please return the item with the label provided.", "请使用提供的标签退回商品。"],
      ["For bulk orders, we can offer better pricing.", "对于批量订单，我们可以提供更好的价格。"],
      ["I have escalated the complaint to our manager.", "我已将投诉升级给经理处理。"],
      ["I will update you before the end of the day.", "我会在今天结束前更新你。"],
      ["Please let us know if anything else comes up.", "如有其他问题请告诉我们。"]
    ]
  }
};

const englishTitles = {
  "机场": "airport check-in",
  "酒店": "hotel check-in",
  "点餐": "restaurant ordering",
  "问路": "asking for directions",
  "会议": "meeting",
  "邮件": "email",
  "汇报": "business report",
  "客户沟通": "customer communication"
};

function dialogueFor(scenario) {
  const isTravel = scenario.category === "travel";
  const englishTitle = englishTitles[scenario.title] ?? "this scenario";
  if (isTravel) {
    return [
      { speaker: "A", en: `Excuse me, I need help with ${englishTitle} information.`, zh: `打扰一下，我需要${scenario.title}相关信息。` },
      { speaker: "B", en: "Of course. What would you like to know?", zh: "当然。你想了解什么？" },
      { speaker: "A", en: scenario.sentences[0][0], zh: scenario.sentences[0][1] },
      { speaker: "B", en: "No problem. Let me check that for you.", zh: "没问题。我帮你确认一下。" },
      { speaker: "A", en: scenario.sentences[3][0], zh: scenario.sentences[3][1] },
      { speaker: "B", en: "Yes, and I recommend arriving a little earlier.", zh: "可以，而且我建议你稍微早点到。" },
      { speaker: "A", en: "Thank you. That is very helpful.", zh: "谢谢，这很有帮助。" },
      { speaker: "B", en: "You're welcome. Have a great trip.", zh: "不客气。祝你旅途愉快。" }
    ];
  }
  return [
    { speaker: "A", en: `Let's discuss the ${englishTitle} update for the e-commerce project.`, zh: `我们讨论一下电商项目的${scenario.title}更新。` },
    { speaker: "B", en: "Sure. What is the main priority today?", zh: "好的。今天最重要的事项是什么？" },
    { speaker: "A", en: scenario.sentences[1][0], zh: scenario.sentences[1][1] },
    { speaker: "B", en: "That makes sense. Do we have any blockers?", zh: "有道理。我们有阻碍吗？" },
    { speaker: "A", en: scenario.sentences[4][0], zh: scenario.sentences[4][1] },
    { speaker: "B", en: "I'll take the follow-up and share an update tomorrow.", zh: "我来跟进，并在明天同步更新。" },
    { speaker: "A", en: "Great. Let's document the next steps.", zh: "很好。我们把下一步记录下来。" },
    { speaker: "B", en: "Agreed. I will send a summary after this.", zh: "同意。我会在之后发送总结。" }
  ];
}

function quizFor(scenario) {
  return scenario.words.slice(0, 10).map(([en, zh], index) => ({
    id: `${scenario.title}-${index + 1}`,
    question: `"${en}" 的中文意思是？`,
    options: [zh, scenario.words[(index + 11) % scenario.words.length][1], scenario.words[(index + 23) % scenario.words.length][1], scenario.words[(index + 37) % scenario.words.length][1]],
    answer: zh
  }));
}

const scenarios = Object.fromEntries(
  Object.entries(seed).map(([id, scenario]) => [
    id,
    {
      id,
      ...scenario,
      words: scenario.words.map(([en, zh, example]) => ({ en, zh, example })),
      sentences: scenario.sentences.map(([en, zh], index) => ({
        en,
        zh,
        scene: scenario.sentenceScenes[index % scenario.sentenceScenes.length]
      })),
      dialogue: dialogueFor(scenario),
      quiz: quizFor(scenario)
    }
  ])
);

mkdirSync("data", { recursive: true });
writeFileSync("data/content.json", `${JSON.stringify({ days, scenarios }, null, 2)}\n`);
